/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppHutangRouteImport } from './routes/_app/hutang'
import { Route as AppKasirRouteImport } from './routes/_app/kasir'
import { Route as AppKeuanganRouteImport } from './routes/_app/keuangan'
import { Route as AppLaporanRouteImport } from './routes/_app/laporan'
import { Route as AppPelangganRouteImport } from './routes/_app/pelanggan'
import { Route as AppPembelianRouteImport } from './routes/_app/pembelian'
import { Route as AppPengaturanRouteImport } from './routes/_app/pengaturan'
import { Route as AppPenggunaRouteImport } from './routes/_app/pengguna'
import { Route as AppProdukRouteImport } from './routes/_app/produk'
import { Route as AppShiftRouteImport } from './routes/_app/shift'
import { Route as AppStokRouteImport } from './routes/_app/stok'
import { Route as AppSupplierRouteImport } from './routes/_app/supplier'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHutangRoute = AppHutangRouteImport.update({
  id: '/hutang',
  path: '/hutang',
  getParentRoute: () => AppRoute,
} as any)
const AppKasirRoute = AppKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AppRoute,
} as any)
const AppKeuanganRoute = AppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppPelangganRoute = AppPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AppRoute,
} as any)
const AppPembelianRoute = AppPembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPenggunaRoute = AppPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AppRoute,
} as any)
const AppProdukRoute = AppProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftRoute = AppShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppRoute,
} as any)
const AppStokRoute = AppStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplierRoute = AppSupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/hutang': typeof AppHutangRoute
  '/kasir': typeof AppKasirRoute
  '/keuangan': typeof AppKeuanganRoute
  '/laporan': typeof AppLaporanRoute
  '/pelanggan': typeof AppPelangganRoute
  '/pembelian': typeof AppPembelianRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/pengguna': typeof AppPenggunaRoute
  '/produk': typeof AppProdukRoute
  '/shift': typeof AppShiftRoute
  '/stok': typeof AppStokRoute
  '/supplier': typeof AppSupplierRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/hutang': typeof AppHutangRoute
  '/kasir': typeof AppKasirRoute
  '/keuangan': typeof AppKeuanganRoute
  '/laporan': typeof AppLaporanRoute
  '/pelanggan': typeof AppPelangganRoute
  '/pembelian': typeof AppPembelianRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/pengguna': typeof AppPenggunaRoute
  '/produk': typeof AppProdukRoute
  '/shift': typeof AppShiftRoute
  '/stok': typeof AppStokRoute
  '/supplier': typeof AppSupplierRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hutang': typeof AppHutangRoute
  '/_app/kasir': typeof AppKasirRoute
  '/_app/keuangan': typeof AppKeuanganRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/pelanggan': typeof AppPelangganRoute
  '/_app/pembelian': typeof AppPembelianRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/pengguna': typeof AppPenggunaRoute
  '/_app/produk': typeof AppProdukRoute
  '/_app/shift': typeof AppShiftRoute
  '/_app/stok': typeof AppStokRoute
  '/_app/supplier': typeof AppSupplierRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/lupa-password'
    | '/reset-password'
    | '/dashboard'
    | '/hutang'
    | '/kasir'
    | '/keuangan'
    | '/laporan'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/pengguna'
    | '/produk'
    | '/shift'
    | '/stok'
    | '/supplier'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/lupa-password'
    | '/reset-password'
    | '/dashboard'
    | '/hutang'
    | '/kasir'
    | '/keuangan'
    | '/laporan'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/pengguna'
    | '/produk'
    | '/shift'
    | '/stok'
    | '/supplier'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/lupa-password'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/hutang'
    | '/_app/kasir'
    | '/_app/keuangan'
    | '/_app/laporan'
    | '/_app/pelanggan'
    | '/_app/pembelian'
    | '/_app/pengaturan'
    | '/_app/pengguna'
    | '/_app/produk'
    | '/_app/shift'
    | '/_app/stok'
    | '/_app/supplier'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hutang': {
      id: '/_app/hutang'
      path: '/hutang'
      fullPath: '/hutang'
      preLoaderRoute: typeof AppHutangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasir': {
      id: '/_app/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AppKasirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keuangan': {
      id: '/_app/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AppKeuanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pelanggan': {
      id: '/_app/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AppPelangganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pembelian': {
      id: '/_app/pembelian'
      path: '/pembelian'
      fullPath: '/pembelian'
      preLoaderRoute: typeof AppPembelianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengguna': {
      id: '/_app/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AppPenggunaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produk': {
      id: '/_app/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof AppProdukRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shift': {
      id: '/_app/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AppShiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok': {
      id: '/_app/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AppStokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supplier': {
      id: '/_app/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof AppSupplierRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHutangRoute: typeof AppHutangRoute
  AppKasirRoute: typeof AppKasirRoute
  AppKeuanganRoute: typeof AppKeuanganRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppPelangganRoute: typeof AppPelangganRoute
  AppPembelianRoute: typeof AppPembelianRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPenggunaRoute: typeof AppPenggunaRoute
  AppProdukRoute: typeof AppProdukRoute
  AppShiftRoute: typeof AppShiftRoute
  AppStokRoute: typeof AppStokRoute
  AppSupplierRoute: typeof AppSupplierRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHutangRoute: AppHutangRoute,
  AppKasirRoute: AppKasirRoute,
  AppKeuanganRoute: AppKeuanganRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppPelangganRoute: AppPelangganRoute,
  AppPembelianRoute: AppPembelianRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPenggunaRoute: AppPenggunaRoute,
  AppProdukRoute: AppProdukRoute,
  AppShiftRoute: AppShiftRoute,
  AppStokRoute: AppStokRoute,
  AppSupplierRoute: AppSupplierRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
