import type { Product, Customer, Supplier, Purchase, Staff } from "./types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "prd_beras",
    name: "Beras Ramos 5 Kg",
    sku: "BRS-5KG",
    barcode: "8991002101001",
    category: "Sembako",
    unit: "pcs",
    buyPrice: 55000,
    sellPrice: 65000,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 18,
    minStock: 5,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_minyak",
    name: "Minyak Goreng 1 L",
    sku: "MYK-1L",
    barcode: "8991002101002",
    category: "Sembako",
    unit: "pcs",
    buyPrice: 14000,
    sellPrice: 18000,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 12,
    minStock: 10,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_gula",
    name: "Gula Pasir 1 Kg",
    sku: "GLA-1KG",
    barcode: "8991002101003",
    category: "Sembako",
    unit: "pcs",
    buyPrice: 14000,
    sellPrice: 16000,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 9,
    minStock: 8,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_indomie",
    name: "Indomie Goreng",
    sku: "IDM-GRG",
    barcode: "8991002101004",
    category: "Makanan",
    unit: "pcs",
    buyPrice: 2500,
    sellPrice: 3500,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 48,
    minStock: 20,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_teh",
    name: "Teh Botol Sosro",
    sku: "TEH-BTL",
    barcode: "8991002101005",
    category: "Minuman",
    unit: "pcs",
    buyPrice: 2500,
    sellPrice: 3000,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 16,
    minStock: 10,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_susu",
    name: "Susu UHT 1 L",
    sku: "SSU-UHT",
    barcode: "8991002101006",
    category: "Minuman",
    unit: "pcs",
    buyPrice: 4500,
    sellPrice: 5500,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 20,
    minStock: 10,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_telur",
    name: "Telur Ayam 1 Kg",
    sku: "TLR-1KG",
    barcode: "8991002101007",
    category: "Sembako",
    unit: "kg",
    buyPrice: 22000,
    sellPrice: 26000,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 10,
    minStock: 5,
    image: "",
    status: "aktif",
  },
  {
    id: "prd_sabun",
    name: "Sabun Mandi",
    sku: "SBN-001",
    barcode: "8991002101008",
    category: "Perawatan",
    unit: "pcs",
    buyPrice: 3500,
    sellPrice: 4500,
    sellPriceDus: 0,
    buyPriceDus: 0,
    pcsPerDus: 1,
    stockDus: 0,
    stock: 22,
    minStock: 8,
    image: "",
    status: "aktif",
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "cst_sari",
    name: "Bu Sari",
    phone: "081234567124",
    totalSpent: 2450000,
    debtTotal: 120000,
    debtRemaining: 120000,
  },
  {
    id: "cst_ahmad",
    name: "Pak Ahmad",
    phone: "081234567878",
    totalSpent: 1870000,
    debtTotal: 0,
    debtRemaining: 0,
  },
  {
    id: "cst_rini",
    name: "Bu Rini",
    phone: "082234567012",
    totalSpent: 3200000,
    debtTotal: 75000,
    debtRemaining: 75000,
  },
  {
    id: "cst_tokokita",
    name: "Toko Kita",
    phone: "081234567456",
    totalSpent: 980000,
    debtTotal: 200000,
    debtRemaining: 200000,
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: "sup_rejeki",
    name: "Toko Sumber Rejeki",
    phone: "081111111111",
    totalPurchase: 2125000,
    debt: 0,
  },
  {
    id: "sup_berkah",
    name: "UD. Berkah Jaya",
    phone: "082222222222",
    totalPurchase: 2300000,
    debt: 0,
  },
  {
    id: "sup_maju",
    name: "CV. Maju Makmur",
    phone: "083333333333",
    totalPurchase: 1560000,
    debt: 560000,
  },
];

export const SEED_PURCHASES: Purchase[] = [
  {
    id: "pch_1",
    date: "2026-10-01",
    supplierId: "sup_rejeki",
    supplierName: "Toko Sumber Rejeki",
    total: 1250000,
    status: "Lunas",
    items: [
      { productId: "prd_beras", name: "Beras Ramos 5 Kg", qty: 10, price: 55000 },
      { productId: "prd_minyak", name: "Minyak Goreng 1 L", qty: 20, price: 14000 },
      { productId: "prd_gula", name: "Gula Pasir 1 Kg", qty: 20, price: 14000 },
    ],
  },
  {
    id: "pch_2",
    date: "2026-09-30",
    supplierId: "sup_berkah",
    supplierName: "UD. Berkah Jaya",
    total: 980000,
    status: "Lunas",
    items: [
      { productId: "prd_indomie", name: "Indomie Goreng", qty: 200, price: 2500 },
      { productId: "prd_teh", name: "Teh Botol Sosro", qty: 80, price: 2500 },
    ],
  },
  {
    id: "pch_3",
    date: "2026-09-28",
    supplierId: "sup_maju",
    supplierName: "CV. Maju Makmur",
    total: 1560000,
    status: "Hutang",
    items: [
      { productId: "prd_susu", name: "Susu UHT 1 L", qty: 80, price: 4500 },
      { productId: "prd_telur", name: "Telur Ayam 1 Kg", qty: 40, price: 22000 },
      { productId: "prd_sabun", name: "Sabun Mandi", qty: 80, price: 3500 },
    ],
  },
  {
    id: "pch_4",
    date: "2026-09-25",
    supplierId: "sup_rejeki",
    supplierName: "Toko Sumber Rejeki",
    total: 875000,
    status: "Lunas",
    items: [
      { productId: "prd_beras", name: "Beras Ramos 5 Kg", qty: 15, price: 55000 },
      { productId: "prd_gula", name: "Gula Pasir 1 Kg", qty: 5, price: 14000 },
    ],
  },
  {
    id: "pch_5",
    date: "2026-09-22",
    supplierId: "sup_berkah",
    supplierName: "UD. Berkah Jaya",
    total: 1320000,
    status: "Lunas",
    items: [
      { productId: "prd_minyak", name: "Minyak Goreng 1 L", qty: 40, price: 14000 },
      { productId: "prd_indomie", name: "Indomie Goreng", qty: 200, price: 2500 },
    ],
  },
];

export const SEED_STAFF: Staff[] = [
  {
    id: "stf_admin",
    name: "Admin Toko",
    username: "admin",
    role: "Administrator",
    isActive: true,
  },
  {
    id: "stf_pagi",
    name: "Kasir Pagi",
    username: "pagi",
    role: "Kasir",
    isActive: true,
  },
  {
    id: "stf_siang",
    name: "Kasir Siang",
    username: "siang",
    role: "Kasir",
    isActive: true,
  },
];
